stages:
- build

build:
  stage: build
  image: golang:1-alpine
  cache:
    paths:
    - .cache
  variables:
    CGO_ENABLED: "0"
  before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - export GOCACHE="$CI_PROJECT_DIR/.cache/build"
  script:
  - go build -o bridge-cd-tool
  artifacts:
    paths:
    - bridge-cd-tool
